dast:
  needs: [test, sonarqube]  # This indicates that the `dast` job runs after `test` and `sonarqube`
  runs-on: ubuntu-latest    # Specifies the environment (Ubuntu) on which this workflow will run
  steps:
    - uses: actions/checkout@v4  # Checkout the repository code
    
    - name: Set up QEMU  # Setting up QEMU to allow multi-platform Docker builds
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx  # Setting up Docker Buildx for advanced Docker builds
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub  # Authenticate with Docker Hub using GitHub secrets
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.tonystark199 }}  # Docker Hub username from secrets
        password: ${{ secrets.dckr_pat_zs2mOMAYy3DkxWKecC0BFHHyl4k }}     # Docker Hub token from secrets

    - name: Build and push  # Build the Docker image and push it to Docker Hub
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-labs:dast-test  # Image name and tag to push
